### ISSUE TITLE
Bug on attach

### ISSUE THREAD

**Issue by Sander2222** [TinusNL/tinus_flatbed#3]
Hey when i want to attach a car to the flatbed and i go in the point then the point disappears and i got this error
![image](https://user-images.githubusercontent.com/86840128/153730865-7d077e32-28c3-4831-8926-31877c43360f.png)

**Comment by TinusNL** [comment]
Which FX Server version are u using? Try updating it because this error is given because of a Native not existing.

**Comment by Sander2222** [comment]
hey, i am using the version: 5208

**Comment by Sander2222** [comment]
i updated it to 5327 and its not working

**Comment by TinusNL** [comment]
It seems like it might be interfering with an onther script. Have you tried running it without any other scripts enabled?

**Comment by Sander2222** [comment]
no, but i try now

**Comment by Sander2222** [comment]
thank you a lot, one script from my was creating this error i am seaching now what for a script (its working)

**Comment by TinusNL** [comment]
Perfect!

**Comment by Sander2222** [comment]
okay it was because of my antiheat: antisalt-anticheat

**Comment by ChickenDipper1** [comment]
> okay it was because of my antiheat: antisalt-anticheat

Did you ever figure out the specific setting causing this?
