### ISSUE TITLE
Vehicle Cam Collision Occuring

### ISSUE THREAD

**Issue by nzkfc** [TinusNL/tinus_flatbed#5]
Seems the vehicle on the back collides with the flatbed truck, I saw there was an update to this but it's happening still?

**Comment by nzkfc** [comment]
Seems to be a bit intermittent, managed to get it to work but then it started again when I restarted the script.

**Comment by marcelo-ds-lopez** [comment]
I was able to resolve it at first.
local LastVehicleAttached = nil set to global.
AttachEntityToEntity(ClosestVehicle.....
LastVehicleAttached = ClosestVehicle assign the car to variable.

  if LastAttach and DoesEntityExist(LastVehicleAttached) then
    DisableCamCollisionForEntity(LastVehicleAttached)
end

**Comment by TinusNL** [comment]
@marcelo-ds-lopez this isn't a 'fix' it basically adds unnecessary variables that do the same as what was already implemented. I just created a new release (V1.0.7) with the actual fix to this issue.
