### ISSUE TITLE
what is happening?

### ISSUE THREAD

**Issue by ghost** [TinusNL/tinus_flatbed#6]
when I ask for flatbed3 this is what appears!

![Nouvelle image bitmap](https://github.com/user-attachments/assets/8fb0b79f-fdea-4070-8079-51358af9127d)

**Comment by TinusNL** [comment]
This is not an issue with this resource. This happens because of a conflict between resources. Try starting this one last or disabling other resources that might be overriding the flatbed3 model.

**Comment by ghost** [comment]
hi, I tried but nothing, I redid on a new base and each time it gives me what you see in the photo, I even tried to change the version of gamebuild... :/
